# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pretrain_model_3d.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(871, 382)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(300, 280, 271, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_load_model = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_load_model.setObjectName("pushButton_load_model")
        self.horizontalLayout_6.addWidget(self.pushButton_load_model)
        self.pushButton_gene_annotation = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_gene_annotation.setObjectName("pushButton_gene_annotation")
        self.horizontalLayout_6.addWidget(self.pushButton_gene_annotation)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(60, 51, 751, 221))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_model_name = QtWidgets.QLabel(self.layoutWidget1)
        self.label_model_name.setObjectName("label_model_name")
        self.horizontalLayout.addWidget(self.label_model_name)
        self.comboBox_model_name = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_model_name.setObjectName("comboBox_model_name")
        self.comboBox_model_name.addItem("")
        self.comboBox_model_name.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_model_name)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_dataset = QtWidgets.QLabel(self.layoutWidget1)
        self.label_dataset.setObjectName("label_dataset")
        self.horizontalLayout_2.addWidget(self.label_dataset)
        self.comboBox_dataset = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_dataset.setObjectName("comboBox_dataset")
        self.comboBox_dataset.addItem("")
        self.comboBox_dataset.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_dataset)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_model_path = QtWidgets.QLabel(self.layoutWidget1)
        self.label_model_path.setObjectName("label_model_path")
        self.horizontalLayout_3.addWidget(self.label_model_path)
        self.textEdit_model_path = QtWidgets.QTextEdit(self.layoutWidget1)
        self.textEdit_model_path.setReadOnly(True)
        self.textEdit_model_path.setObjectName("textEdit_model_path")
        self.horizontalLayout_3.addWidget(self.textEdit_model_path)
        self.pushButton_config_model_path = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_config_model_path.setObjectName("pushButton_config_model_path")
        self.horizontalLayout_3.addWidget(self.pushButton_config_model_path)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_image_dir = QtWidgets.QLabel(self.layoutWidget1)
        self.label_image_dir.setObjectName("label_image_dir")
        self.horizontalLayout_4.addWidget(self.label_image_dir)
        self.textEdit_image_dir = QtWidgets.QTextEdit(self.layoutWidget1)
        self.textEdit_image_dir.setReadOnly(True)
        self.textEdit_image_dir.setObjectName("textEdit_image_dir")
        self.horizontalLayout_4.addWidget(self.textEdit_image_dir)
        self.pushButton_config_image_dir = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_config_image_dir.setObjectName("pushButton_config_image_dir")
        self.horizontalLayout_4.addWidget(self.pushButton_config_image_dir)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_annotation_dir = QtWidgets.QLabel(self.layoutWidget1)
        self.label_annotation_dir.setObjectName("label_annotation_dir")
        self.horizontalLayout_7.addWidget(self.label_annotation_dir)
        self.textEdit_annotation_dir = QtWidgets.QTextEdit(self.layoutWidget1)
        self.textEdit_annotation_dir.setReadOnly(True)
        self.textEdit_annotation_dir.setObjectName("textEdit_annotation_dir")
        self.horizontalLayout_7.addWidget(self.textEdit_annotation_dir)
        self.pushButton_config_annotation_dir = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_config_annotation_dir.setObjectName("pushButton_config_annotation_dir")
        self.horizontalLayout_7.addWidget(self.pushButton_config_annotation_dir)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_progress = QtWidgets.QLabel(self.layoutWidget1)
        self.label_progress.setObjectName("label_progress")
        self.horizontalLayout_5.addWidget(self.label_progress)
        self.progressBar_proc = QtWidgets.QProgressBar(self.layoutWidget1)
        self.progressBar_proc.setProperty("value", 0)
        self.progressBar_proc.setObjectName("progressBar_proc")
        self.horizontalLayout_5.addWidget(self.progressBar_proc)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 871, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_load_model.clicked.connect(MainWindow.on_pushbutton_load_model)
        self.pushButton_gene_annotation.clicked.connect(MainWindow.on_pushbutton_generate_annotations)
        self.pushButton_config_model_path.clicked.connect(MainWindow.on_pushbutton_config_model_path)
        self.pushButton_config_image_dir.clicked.connect(MainWindow.on_pushbutton_config_image_dir)
        self.pushButton_config_annotation_dir.clicked.connect(MainWindow.on_pushbutton_config_annotation_dir)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_load_model.setText(_translate("MainWindow", "load model"))
        self.pushButton_gene_annotation.setText(_translate("MainWindow", "generate annotations"))
        self.label_model_name.setText(_translate("MainWindow", "model:"))
        self.comboBox_model_name.setItemText(0, _translate("MainWindow", "CenterLoc3D"))
        self.comboBox_model_name.setItemText(1, _translate("MainWindow", "CenterDet3D"))
        self.label_dataset.setText(_translate("MainWindow", "dataset:"))
        self.comboBox_dataset.setItemText(0, _translate("MainWindow", "common"))
        self.comboBox_dataset.setItemText(1, _translate("MainWindow", "cross"))
        self.label_model_path.setText(_translate("MainWindow", "model path:"))
        self.pushButton_config_model_path.setText(_translate("MainWindow", "..."))
        self.label_image_dir.setText(_translate("MainWindow", "image dir:"))
        self.pushButton_config_image_dir.setText(_translate("MainWindow", "..."))
        self.label_annotation_dir.setText(_translate("MainWindow", "annotation dir:"))
        self.pushButton_config_annotation_dir.setText(_translate("MainWindow", "..."))
        self.label_progress.setText(_translate("MainWindow", "0/0:"))

